
modLoader="javafml" #mandatory

loaderVersion="[33,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="foodstuffs" #mandatory

version="1.16.4-1.0.0" #mandatory

displayName="Foodstuffs" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Thanks to Bonniethebunny and everyone else on our discord server" #optional

authors="Parabaum, BonnieBread" #optional

description='''
We add stuff about food
'''

[[dependencies.examplemod]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[33,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
